name: Python CI

# Trigger the workflow on any push to the main branch or pull request
on:
  push:
    branches: 
    - main
  pull_request:
    branches: 
    - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # Step 1: check out the code from the repository
    - uses: actions/checkout@v2
    - name: check out the code

    # Step 2: set up python environment
    - uses: actions/checkout@v4
    - name: Set up Python '3.10'
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    # Step 3: Install all the dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Step 4: runs test
    - name: Test with pytest
      run: |
        pytest
